# Generated by Django 2.2.7 on 2019-12-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clients_photos'),
        ),
    ]
